export const team = [
  {
    name: 'Tuomo Kujala',
    role: 'Professor · Project Leader',
    bio: 'Studies human attention allocation and inattention in dynamic tasks, with the aim of developing less distracting interfaces and safer driver-support systems.',
    photo: 'https://www.jyu.fi/sites/default/files/styles/1_1_300px/public/profiles/Tuomo_Kujala_1bfdf51a7f43eef1d22b3df7a554835c_1786741739.jpg?h=fbf7a813&itok=vJIs9Ekh',
    email: 'tuomo.kujala@jyu.fi',
    phone: '+358 40 024 7392',
    profile: 'https://www.jyu.fi/en/people/tuomo-kujala',
  },
  {
    name: 'Toni Hautaoja',
    role: 'Doctoral Researcher',
    bio: 'Researches driver attention and computational models of attention allocation in vehicle control.',
    photo: 'https://www.jyu.fi/sites/default/files/styles/1_1_300px/public/profiles/Toni_Hautaoja_41e3493accb3953178d0e4a31e0426c4_1785934178.jpg?h=fbf7a813&itok=jf518BDk',
    email: 'toni.n.a.hautaoja@jyu.fi',
    phone: '+358 50 478 7158',
    profile: 'https://www.jyu.fi/en/people/toni-hautaoja',
  },
  {
    name: 'Juuso-Petteri Partanen',
    role: 'Research Assistant',
    bio: 'Supports research and study work in the Faculty of Information Technology and the Drive-In Lab team.',
    photo: null,
    email: 'juuso-petteri.m.partanen@jyu.fi',
    phone: '+358 50 331 4294',
    profile: 'https://www.jyu.fi/en/people/juuso-petteri-partanen',
  },
  {
    name: 'Aaron Khodami',
    role: 'Postdoctoral Researcher',
    bio: 'Studies vision, visual attention, eye tracking, EEG, and behavioural modelling in the Cognitive Science division.',
    photo: 'https://www.jyu.fi/sites/default/files/styles/1_1_300px/public/profiles/Aaron_Khodami_55846ddc2684509b297fb0fdd3f16689_1781003113.jpg?h=fbf7a813&itok=FjahGhHu',
    email: 'aaron.a.khodami@jyu.fi',
    phone: null,
    profile: 'https://www.jyu.fi/en/people/aaron-khodami',
  },
]
